config/routes.rb
Rails.application.routes.draw do

  root 'cinemas#index'

  resources :cinemas, only: [:index, :show] do
		member do
      constraints(format: "json") do
        get 'ping'
      end
		end
	end

end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
	belongs_to :show
	validates_presence_of :name, :show_time, :end_time

	scope :active,->{where('end_time > ?', Time.now)}
	def is_active?
		Time.now < self.end_time
	end
end

app/models/show.rb
class Show < ActiveRecord::Base
	has_many :cinema
	validates_presence_of :name, :player_url, :number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :show_title

  def show_title
  	@show_title = Cinema.find_by_id(params[:id]).show.name unless Cinema.find_by_id(params[:id]).nil?
  end
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
	before_filter :find_cinema, only: [:show, :ping]
	def index
		@cinemas = Cinema.active
	end

	def show
	end

	def ping
		if @cinema.is_active?
			time_lapsed = (Time.now - @cinema.show_time).to_i
			render json: {time: time_lapsed}
		else
			render json: {time: -1}
		end
	end

	private
	def find_cinema
		@cinema = Cinema.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
	def duration(time) 
		secs = time.to_i
		mins  = secs / 60
		hours = mins / 60
		days  = hours / 24

		if days > 0
			"#{days} days and #{hours % 24} hours"
		elsif hours > 0
			"#{hours} hours and #{mins % 60} minutes"
		elsif mins > 0
			"#{mins} minutes and #{secs % 60} seconds"
		elsif secs >= 0
			"#{secs} seconds"
		end
	end 
end

app/views/cinemas/index.html.erb
<div class="container">
	<div class="cinema-list">
		<h1 class="header-title">Cinema List</h1>
		<ul class="cinema">
			<% @cinemas.each do |cinema| %>
				<li>
					<%= image_tag(cinema.show.image_url, class: 'thumbnail', size: "220x123") %>
					<div class="cinema-info">
						<h1><%= cinema.show.name %>
							<% if cinema.show.number > 0 %>
								<%= "- Episode #{cinema.show.number}" %>
							<% end %>
						</h1>
						<% if (cinema.show_time < Time.now) %>
							<span class="info info-live">Now Showing</span>
						<% else %>
							<span class="info info-coming">Start in <%= duration(cinema.show_time - Time.now) %></span>
						<% end %>
						<span class="info info-hall"><%= cinema.name %></span>
						<p><%= cinema.show.description %></p>
					</div>
					<% if cinema.show_time < Time.now %>
						<div class="buttons"><a class="btn btn-watch" href="<%= cinema_path(cinema) %>">Watch Now</a></div>
					<% else %>
						<div class="buttons btn btn-coming-soon">Coming Up<div>

					<% end %>
				</li> 
			<% end %>
		</ul>
	</div>
</div>

app/views/cinemas/show.html.erb
<%= javascript_tag do %>
    $(document).ready(function() {
        setInterval(function(){
            $.ajax({
                type: "GET",
                url: "/cinemas/<%= @cinema.id %>/ping",
                dataType: "JSON"
            }).success(function(msg) {
                var result = $.parseJSON(JSON.stringify(msg));
                console.log('Sever time: ' + result.time);
                if (result.time < 0){
                    window.player.pauseVideo();
                }
                else{
                    var currTime = window.player.getCurrentTime();
                    console.log('Flash player time: ' + currTime);
                    if (Math.abs(result.time - currTime) > 10){
                        window.player.seekTo(result.time);
                    }
                }
            });
        }, 1000);
        window.player.init();
    })
<% end %>

<div class="chat">
  <div class="info">
  </div>
  <iframe src="http://localhost:3000?channel=<%= @cinema.id %>" width="250" height="95%" frameBorder="0"></iframe>
</div>
<%
   flash_config = {
           plugins: {
                   api: {
                           autoplay: true,
                           autostart: true,
                           discussions: "off",
                           subtitles: "on",
                           show_comments: false,
                           show_subtitles: true,
                           chromeless: params["chromeless"].present? ? params["chromeless"] == "true": false,
                           timestamp: Time.now.to_i,
                           playlist: [@cinema.show.player_url],
                           volume: params.has_key?("volume") ? params["volume"].to_i : -1,
                   }
           }
   }
   flash_config = Oj.dump(flash_config, mode: :compat).html_safe
%>
<div id="viki-player" class="player">
  <!-- Change size here, for now. I am working on making it responsive -->

  <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="flashObject" align="middle">
    <param name="movie" value="http://0.viki.io/a/player.swf"/>
    <param name="quality" value="high"/>
    <param name="wmode" value="opaque"/>
    <param name="allowScriptAccess" value="always"/>
    <param name="allowFullScreen" value="true"/>
    <param name="bgcolor" value="#000000">
    <param name="flashvars" value='config=<%= flash_config %>'>
    <!--[if !IE]>-->
    <object type="application/x-shockwave-flash" data="http://0.viki.io/a/player.swf" width="100%" height="100%">
      <param name="movie" value="http://0.viki.io/a/player.swf"/>
      <param name="quality" value="high"/>
      <param name="wmode" value="opaque"/>
      <param name="allowScriptAccess" value="always"/>
      <param name="allowFullScreen" value="true"/>
      <param name="bgcolor" value="#000000">
      <param name="flashvars" value='config=<%= flash_config %>'>
      <embed src="http://0.viki.io/a/player.swf">
        <!--<![endif]-->
        <!--<a href="http://www.adobe.com/go/getflash">
          <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player"/>
        </a> -->
        <!--[if !IE]>-->
    </object>
    <!--<![endif]-->
  </object>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VikiCinema</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="mainbar">
  <div class="title">
    <%= link_to image_tag("viki-logo.png", :class => "logo"), root_path() %>
    <span class="sub-title"><%= link_to "Cinema", root_path() %></span>
  </div>
  <% if @show_title.present? %>
  	<h1 class="now-watching"> Now watching - <%= @show_title %></h1>
  <% end %>
</div>

<%= yield %>

</body>
</html>